parameters:
    mail_forwarding:
        path: "/set/path/to/forwarding/file"


services:

    mail_forwarding_service:
        class: SAS\IRAD\MailForwardingBundle\Service\MailForwardingService
        arguments:  [ @file.storage, @account_logger, %mail_forwarding%, %google_params% ]

