services:

    ## service for penngroups queries
    penngroups.ldap_query:
        class: Penn\PennGroupsBundle\Service\LDAPQuery
        #arguments:  [ "%penn_groups.username%", "%penn_groups.credential%", "%penn_groups.key%" ]

    penngroups.web_service_query:
        class: Penn\PennGroupsBundle\Service\WebServiceQuery
        arguments:  [ "%penngroups%" ]        