account_log:
    resource: "@AccountLogBundle/Controller/"
    type:     annotation
    prefix:   /admin/accountLog

oauth2_token:
    resource: "@OAuth2TokenBundle/Controller"
    type:     annotation
    prefix:   /admin/token
