gmail_configure:
    resource: "@GMailConfigureBundle/Controller/"
    type:     annotation
    prefix:   /gmail

mail_forwarding:
    resource: "@MailForwardingBundle/Controller/"
    type:     annotation
    prefix:   /forward

account_log:
    resource: "@GmailAccountLogBundle/Controller/"
    type:     annotation
    prefix:   /admin/accountLog

oauth2_token:
    resource: "@GoogleOAuth2TokenBundle/Controller"
    type:     annotation
    prefix:   /admin/token
